remote_theme: pmarsceill/just-the-docs
title: Open Science in Phytolith Research
nav_exclude: true
description: Let’s make phytolith research better by moving into the era of open science!
# Aux links for the upper right navigation
baseurl: "/Open-Science-in-Phytolith-Research" # the subpath of your site, e.g. /blog
url: "https://github.com/EKaroune/" # the base hostname & protocol for your site, e.g. http://example.com
aux_links:
  "View on GitHub": "https://github.com/EKaroune/Open-Science-in-Phytolith-Research "
# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2020 Emma Karoune. Distributed under a <a href=\"http://ekaroune.github.io/Open-Science-in-Phytolith-Research\">CC-BY-4.0 license.</a>"
# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/EKaroune/Open-Science-in-Phytolith-Research" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
color_scheme: light
logo: 
plugins:
  - jemoji

